spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host:192.168.1.77:3306}/${db.name:awakening_insects}?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: ${db.username:root}
    password: ${db.password:123456}
    hikari:
      auto-commit: false